// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baaraco/baara/pkg/ai (interfaces: Generator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_generator.go -package=mocks github.com/baaraco/baara/pkg/ai Generator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ai "github.com/baaraco/baara/pkg/ai"
	models "github.com/baaraco/baara/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockGenerator) Generate(arg0, arg1 string, arg2 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockGeneratorMockRecorder) Generate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGenerator)(nil).Generate), arg0, arg1, arg2)
}

// GenerateScorecard mocks base method.
func (m *MockGenerator) GenerateScorecard(arg0 ai.ScorecardInput) ([]models.ScorecardCriterion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateScorecard", arg0)
	ret0, _ := ret[0].([]models.ScorecardCriterion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateScorecard indicates an expected call of GenerateScorecard.
func (mr *MockGeneratorMockRecorder) GenerateScorecard(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateScorecard", reflect.TypeOf((*MockGenerator)(nil).GenerateScorecard), arg0)
}

// GenerateWorkSample mocks base method.
func (m *MockGenerator) GenerateWorkSample(arg0 ai.WorkSampleInput) (*models.JobWorkSampleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateWorkSample", arg0)
	ret0, _ := ret[0].(*models.JobWorkSampleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateWorkSample indicates an expected call of GenerateWorkSample.
func (mr *MockGeneratorMockRecorder) GenerateWorkSample(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateWorkSample", reflect.TypeOf((*MockGenerator)(nil).GenerateWorkSample), arg0)
}

// IsConfigured mocks base method.
func (m *MockGenerator) IsConfigured() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfigured")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConfigured indicates an expected call of IsConfigured.
func (mr *MockGeneratorMockRecorder) IsConfigured() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfigured", reflect.TypeOf((*MockGenerator)(nil).IsConfigured))
}
